### ISSUE TITLE
tesseractOCR_umi_plugin排版解析方案一定要设为“不做处理”吗？

### ISSUE THREAD

**Issue by zhang569786645** [hiroi-sora/Umi-OCR_plugins#5]
我设置成其他的好像也可以使用呀，还有要使用这个插件是不是必须先把原来自带的插件删掉？有办法不删除原来的插件，在OCR里选择使用哪个插件吗？

**Comment by zhang569786645** [comment]
我在识别两列数字（两列文字中间有空格）的时候，想让这两列文字位于EXCEL的两列单元格里。如果排版设置成 不做处理 ， 识别后两列数字全部被放入一个单元格了，这不是我想要的结果。目前我是使用排版为 单栏-保留缩进  复制粘贴进excel，会把识别文字列为一栏，再用excel里的分列功能把两列文字拆开，变成两列。 请问有更好的办法吗？

**Comment by hiroi-sora** [comment]
> 识别两列数字（两列文字中间有空格）

一个取巧的办法是每列数字单独截图，分别截取左右两张图，得到两列结果，粘贴进Excel里。

可以对比一下，这种方法和手动调用Excel的分列比，哪个更方便。
