### ISSUE TITLE
win7_x64_TesseractOCR_best_v1.1.0 解压出来提示 插件加载错误?

### ISSUE THREAD

**Issue by gujin162** [hiroi-sora/Umi-OCR_plugins#6]
win7_x64_TesseractOCR_best_v1.1.0: 动态导入包失败：No module named 'win7_x64_TesseractOCR_best_v1'
win7_x64_TesseractOCR_fast_v1.1.0: 动态导入包失败：No module named 'win7_x64_TesseractOCR_fast_v1'

**Comment by hiroi-sora** [comment]
https://github.com/qwedc001/tesseractOCR_umi_plugin/issues/11
