### ISSUE TITLE
大佬，能再详细地介绍一下插件之间地差别吗，还有装插件和直接用原程序的差别

### ISSUE THREAD

**Issue by tcmtom** [hiroi-sora/Umi-OCR_plugins#7]
现在看描述感觉还是分不太清之间的区别

**Comment by hiroi-sora** [comment]
装插件和直接使用 Umi-OCR_xxxx 的发行版是等价的。比如 Umi-OCR_Paddle_v2.1.1 ，其实就是内置了 `win7_x64_PaddleOCR-json` 的插件。如果你再手动放一个 `win7_x64_RapidOCR-json` 的插件，然后在全局设置中切换过来，那么它就跟 Umi-OCR_Rapid_v2.1.1 完全一致了。

各个插件最主要的特点：

- **PaddleOCR**：速度快，CPU占用极高，不兼容部分低端CPU。
- **RapidOCR**：相当于Paddle的”轻量版“，准确率差不多，速度慢点，CPU占用低、兼容性好。
- **Pix2Text**：唯一支持 **数学公式识别** 的插件（用法跟文字OCR一样），而且公式识别的准确率相当不错。文字识别方面跟PaddleOCR近似，不过仅支持中英文。
- **TesseractOCR**：长篇英文文本的准确率和排版还原度不错，其余方面不如别的插件。
- **ChineseOCR**：没啥优势。

**Comment by hiroi-sora** [comment]
文档已改
